// @ts-nocheck
import { Context } from 'cordis';
import { Logger } from '@ejunz/utils';
import { sendVTuberControl } from '../client/vtuber-server';
import { config } from '../config';

const logger = new Logger('client-mcp');

export interface ClientToolDefinition {
    name: string;
    description: string;
    inputSchema: any;
    metadata?: Record<string, any>;
}

export interface ClientToolRegistryEntry {
    tool: ClientToolDefinition;
    handler: (ctx: Context, args: any) => Promise<any>;
    metadata?: Record<string, any>;
}

// 10个VTuber动作表情的定义
const VTUBER_ACTIONS = [
    {
        id: 'happy_nod',
        name: 'vtuber_happy_nod',
        description: '触发开心+点头动作',
    },
    {
        id: 'confused',
        name: 'vtuber_confused',
        description: '触发疑惑表情',
    },
    {
        id: 'shake_head_around',
        name: 'vtuber_shake_head_around',
        description: '触发摇头晃脑动作',
    },
    {
        id: 'shy',
        name: 'vtuber_shy',
        description: '触发平静+害羞表情',
    },
    {
        id: 'idle_tilt_head',
        name: 'vtuber_idle_tilt_head',
        description: '触发发呆+歪头动作',
    },
    {
        id: 'excited_dance',
        name: 'vtuber_excited_dance',
        description: '触发开心+手舞足蹈动作',
    },
    {
        id: 'surprised_blink',
        name: 'vtuber_surprised_blink',
        description: '触发惊讶+眨眼动作',
    },
    {
        id: 'excited_wave',
        name: 'vtuber_excited_wave',
        description: '触发兴奋+挥手动作',
    },
    {
        id: 'surprised',
        name: 'vtuber_surprised',
        description: '触发吃惊表情',
    },
    {
        id: 'sad',
        name: 'vtuber_sad',
        description: '触发难过表情',
    },
];

// 调用VTuber动作的工具处理函数
async function callVTuberActionTool(
    ctx: Context,
    actionId: string,
    args: { duration?: number; intensity?: number }
): Promise<any> {
    const { duration = 2000, intensity = 0.6 } = args;
    
    logger.info('调用VTuber动作: %s (duration: %d, intensity: %.2f)', actionId, duration, intensity);
    
    try {
        // 发送VTuber控制指令
        sendVTuberControl({
            type: 'action',
            action: {
                name: actionId,
                duration,
                intensity,
                blend: true,
            },
        });
        
        return {
            success: true,
            action: actionId,
            message: `已触发动作: ${actionId}`,
            duration,
            intensity,
        };
    } catch (error: any) {
        logger.error('调用VTuber动作失败: %s', error.message);
        throw new Error(`触发动作失败: ${error.message}`);
    }
}

// 构建基础工具条目
function buildBaseToolEntries(): Array<[string, ClientToolRegistryEntry]> {
    const entries: Array<[string, ClientToolRegistryEntry]> = [];
    
    // 检查vtuber是否启用
    const vtuberConfig = (config as any).voice?.vtuber || (config as any).vtuber || {};
    if (vtuberConfig.enabled !== false) {
        // 为每个VTuber动作创建工具
        for (const action of VTUBER_ACTIONS) {
            entries.push([
                action.name,
                {
                    tool: {
                        name: action.name,
                        description: action.description,
                        inputSchema: {
                            type: 'object',
                            properties: {
                                duration: {
                                    type: 'number',
                                    description: '动作持续时间（毫秒），默认2000',
                                    default: 2000,
                                },
                                intensity: {
                                    type: 'number',
                                    description: '动作强度（0-1），默认0.6',
                                    default: 0.6,
                                },
                            },
                            required: [],
                        },
                        metadata: {
                            category: 'client-vtuber',
                            actionId: action.id,
                        },
                    },
                    handler: async (ctx: Context, args: any) => {
                        return await callVTuberActionTool(ctx, action.id, args);
                    },
                    metadata: {
                        category: 'client-vtuber',
                        autoGenerated: false,
                    },
                },
            ]);
        }
    }
    
    return entries;
}

const clientToolRegistry = new Map<string, ClientToolRegistryEntry>(buildBaseToolEntries());

// 获取所有 Client 工具列表
export function listClientTools(includeMetadata = false): ClientToolDefinition[] {
    return Array.from(clientToolRegistry.values()).map((entry) => {
        if (!includeMetadata) return entry.tool;
        return {
            ...entry.tool,
            metadata: {
                ...(entry.tool.metadata || {}),
                ...(entry.metadata || {}),
            },
        };
    });
}

export function getClientToolEntry(name: string): ClientToolRegistryEntry | undefined {
    return clientToolRegistry.get(name);
}

// 调用 Client 工具
export async function callClientTool(ctx: Context, request: { name: string; arguments: any }): Promise<any> {
    const { name, arguments: args } = request;
    const startTime = Date.now();
    
    // 记录工具调用开始
    logger.info('[MCP工具调用] %s 参数: %o', name, args);
    
    const entry = clientToolRegistry.get(name);
    if (!entry) {
        logger.error('[MCP工具调用] 未知工具: %s', name);
        throw new Error(`Unknown client tool: ${name}`);
    }
    
    try {
        const result = await entry.handler(ctx, args);
        const duration = Date.now() - startTime;
        
        // 记录工具调用成功
        const resultPreview = typeof result === 'object' 
            ? JSON.stringify(result).substring(0, 200) 
            : String(result).substring(0, 200);
        logger.success('[MCP工具调用] %s 成功 (耗时: %dms) 结果: %s', name, duration, resultPreview);
        
        return result;
    } catch (error) {
        const duration = Date.now() - startTime;
        logger.error('[MCP工具调用] %s 失败 (耗时: %dms) 错误: %s', name, duration, (error as Error).message);
        throw error;
    }
}

